version: "4.34.3"
services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run pageObjCh
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
